In [1]:
import numpy as np

In [2]:
np.array([1,10,21,35,72])

array([ 1, 10, 21, 35, 72])

In [3]:
np.array([[9,8,7],[6,5,4],[3,2,1]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [4]:
np.arange(start=1, stop=10, step=1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array_1 = np.linspace(0,20,6)
array_2 = np.arange(0,20,6)
print(array_1)
print(array_2)


[ 0.  4.  8. 12. 16. 20.]
[ 0  6 12 18]


In [8]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])
mat.mean()



np.float64(131.66666666666666)

In [10]:
a = np.arange(0,20)
print(a)
print(a[2:7])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 3 4 5 6]


In [11]:
np.cos([0,1,2,3,4])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [13]:
list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2
print(new_list)

[1, 2, 3, 4, 5, 6]


In [14]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
print(new_array)

[5 7 9]


In [18]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[2]=5
print(mat)

[[1 2 1]
 [4 5 9]
 [5 5 5]]


In [19]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

21


In [22]:
print(np.ones([2,2]))

[[1. 1.]
 [1. 1.]]


In [23]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
print(n1)
print(n2)
print(n1*n2)

[[121 144 169]
 [196 225 256]
 [289 324 361]]
[[1 4 9]
 [1 5 4]
 [9 4 8]]
[[1786 1880 3017]
 [2725 2933 4712]
 [3862 4220 6785]]
